# Generated by Django 4.2.24 on 2025-09-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoinHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coin_symbol", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField()),
                ("open_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("volume", models.DecimalField(decimal_places=8, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["coin_symbol", "timestamp"],
                        name="predictor_c_coin_sy_743377_idx",
                    )
                ],
            },
        ),
    ]
